# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

permissions:
  contents: read

jobs:
  shared-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
    id: cache
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
      restore-keys: | 
        ${{ runner.os }}-pip-

  app-build:      
    runs-on: ubuntu-latest
    needs: shared-build
    steps:
    - name: Install dependencies app
      run: |
        cd app
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    
  api-build:      
    runs-on: ubuntu-latest
    needs: shared-build
    steps:
    - name: Install dependencies api
      run: |
        cd API
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
    - name: Test API with pytest
      run: |
        cd API
        pytest