# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push]

permissions:
  contents: read

jobs:
  shared-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          app
          API
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

  app-build:      
    runs-on: ubuntu-latest
    needs: shared-build
    steps:
    - name: Install dependencies app
      run: pip install -r requirements.txt
      working-directory: app

  api-build:      
    runs-on: ubuntu-latest
    needs: shared-build
    steps:
    - name: Install dependencies api
      run: pip install -r requirements.txt
      working-directory: API
    - name: Test API with pytest
      run: pytest
      working-directory: API