name: Build and deploy on AWS workflow

on: [push]

permissions:
  contents: read

jobs:
  shared-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
        restore-keys: | 
          ${{ runner.os }}-pip-
    - name: Upgrade pip
      run: python -m pip install --upgrade pip

  app-build:      
    runs-on: ubuntu-latest
    needs: shared-build
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies app
      run: pip install -r requirements.txt

  api-build:      
    runs-on: ubuntu-latest
    needs: shared-build
    defaults:
      run:
        working-directory: api
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies api
      run: pip install -r requirements.txt
    - name: Test API with pytest
      run: pytest

  deploy-aws:
    runs-on: ubuntu-latest
    needs: ['app-build', 'api-build']
    steps:
    - uses: actions/checkout@v4
    - name: Login and deploy to AWS
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd credit_scoring
            git pull ${{ secrets.GH_CONNECTION }}
            docker compose down
            docker rmi credit_scoring-app
            docker rmi credit_scoring-api
            docker system prune -f
            docker compose up -d